### ISSUE TITLE
Horizontal scrolling on 'About' page

### ISSUE THREAD

**Issue by mattrberry** [Abbondanzo/PersonalWebsite#2]
You are able to scroll horizontally to the right on https://abbondanzo.com/about.

**Comment by Abbondanzo** [comment]
Can you please provide environment details so that I may recreate this issue such as:

- Operating System
- Browser (and version)
- Script-blocking browser extensions (i.e. Ghostery, uBlock)
- Screen dimension

**Comment by mattrberry** [comment]
- Ubuntu 16.04
- Chrome 59
- None
- 1080p

**Comment by Abbondanzo** [comment]
Working as designed
